x-veld:
  code:
    description: "removes all lines before and after given line numbers"
    topic: 
      - "NLP"
      - "preprocessing"
      - "ETL"

    input:
      - volume: /veld/input/
        environment_var: in_file
        file_type: "txt"
        content: "raw text"

    output:
      - volume: /veld/output/
        environment_var: out_file
        file_type: "txt"
        content: "raw text"

    config:
      - environment_var: line_start
        description: "line number before which lines will be stripped away. E.g. line_start=50
          removes lines from 1-49"
        var_type: "int" 
      - environment_var: line_end
        description: "line number after which lines will be stripped away. E.g. line_end=100 removes
          lines from 101-end"
        var_type: "int" 

services:
  veld_preprocess_strip:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: /veld/code/preprocess_strip.sh
    environment:
      in_file: null
      out_file: null
      line_start: null
      line_end: null

